### ISSUE TITLE
folding array over string doesn't work

### ISSUE THREAD

**Issue by outbounder** [outbounder/organic-dna-fold#1]
the following dna 

```
{
  "modeA": {
    "property": [
      'array-value-1',
      'array-value-2'
    ]
  },
  "property": 'string-value'
}
```

Is folded without replacing `property` value from string to array.

An workaround is to use override without merge like

```
{
  "modeA": {
    "~property": [
      'array-value-1',
      'array-value-2'
    ]
  },
  "property": 'string-value'
}
```

**Comment by dirchev** [comment]
Folding array over boolean does not work too.

**Comment by outbounder** [comment]
resolved in https://github.com/outbounder/organic-dna-fold/commit/b3849b8870f356a86d2f1628666ddfab1dbebe69

@dirchev thanks for pointing that out too. 
Note that this module is often used as part of [organic-dna-loader](https://www.npmjs.com/package/organic-dna-loader) -> [organic-dna-cellmodes](https://github.com/outbounder/organic-dna-cellmodes) so it should be enough just to re-install organic-dna-loader. If not please file an issue in organic-dna-loader to do a fresh release ;)
